"""Core types and functions for planted Minesweeper CSP instances."""

from .bp import (
    BPConfig,
    BPInitialization,
    BPMarginalComparison,
    BPMultipleResult,
    BPResult,
    BPStatus,
    compare_bp_to_exact,
    run_bp,
    run_bp_multiple,
)
from .candidate import (
    analyze_candidate_directory,
    build_candidate_plan,
    execute_candidate_plan,
    identify_candidate_region,
    score_candidate_points,
    write_candidate_plan,
)
from .exact import (
    ExactEnumerationLimitError,
    ExactResult,
    OverlapDistribution,
    enumerate_feasible_states,
    solve_exact,
)
from .factor_graph import (
    FactorGraph,
    assert_csp_consistent,
    build_factor_graph,
    check_csp_consistency,
    constraint_residuals,
)
from .instance import PlantedInstance, generate_ground_truth
from .diagnostics import (
    effective_sample_size,
    gelman_rubin_r_hat,
    integrated_autocorrelation_time,
)
from .experiment import (
    SweepExperimentConfig,
    derive_seed,
    execute_sweep,
    load_sweep_config,
    prepare_output_directory,
    run_disorder_sample,
)
from .mcmc import (
    MCMCConfig,
    MCMCMarginalComparison,
    MCMCMultipleResult,
    MCMCResult,
    compare_mcmc_to_exact,
    run_blocked_gibbs,
    run_blocked_gibbs_chains,
)
from .observation import (
    ObservationProtocol,
    generate_clues,
    generate_observation_mask,
    iter_neighbor_cells,
)
from .theory import (
    BetheResult,
    FactorGraphTopology,
    RSStabilityLimitError,
    RSStabilityResult,
    analyze_rs_candidate_directory,
    analyze_rs_run,
    compute_bethe_result,
    compute_rs_stability,
    factor_graph_topology,
)

__all__ = [
    "BPConfig",
    "BPInitialization",
    "BPMarginalComparison",
    "BPMultipleResult",
    "BPResult",
    "BPStatus",
    "analyze_candidate_directory",
    "build_candidate_plan",
    "FactorGraph",
    "ExactEnumerationLimitError",
    "ExactResult",
    "ObservationProtocol",
    "OverlapDistribution",
    "PlantedInstance",
    "SweepExperimentConfig",
    "assert_csp_consistent",
    "build_factor_graph",
    "check_csp_consistency",
    "compare_bp_to_exact",
    "constraint_residuals",
    "compare_mcmc_to_exact",
    "effective_sample_size",
    "derive_seed",
    "execute_sweep",
    "execute_candidate_plan",
    "enumerate_feasible_states",
    "generate_clues",
    "generate_ground_truth",
    "generate_observation_mask",
    "gelman_rubin_r_hat",
    "integrated_autocorrelation_time",
    "identify_candidate_region",
    "load_sweep_config",
    "prepare_output_directory",
    "iter_neighbor_cells",
    "run_bp",
    "run_bp_multiple",
    "run_blocked_gibbs",
    "run_blocked_gibbs_chains",
    "run_disorder_sample",
    "score_candidate_points",
    "solve_exact",
    "MCMCConfig",
    "MCMCMarginalComparison",
    "MCMCMultipleResult",
    "MCMCResult",
    "write_candidate_plan",
    "BetheResult",
    "FactorGraphTopology",
    "RSStabilityLimitError",
    "RSStabilityResult",
    "analyze_rs_candidate_directory",
    "analyze_rs_run",
    "compute_bethe_result",
    "compute_rs_stability",
    "factor_graph_topology",
]
